name: Language Workflow

on:
  push:
    branches:
      - lang

jobs:
  french_job:
    if: ${{ vars.LANG == 'FR' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print French Message
        run: echo "L'utilisateur ${{ github.actor }} parle français"

  english_job:
    if: ${{ vars.LANG != 'FR' }}
    runs-on: ubuntu-latest
    steps:
      - name: Print English Message
        run: echo "User  ${{ github.actor }} speaks English"
